/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as eventFactorySol from "./EventFactory.sol";
export type { eventFactorySol };
export type { ArenaEvent } from "./ArenaEvent";
