/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Foxcon2022__factory } from "./Foxcon2022__factory";
export { Migrations__factory } from "./Migrations__factory";
