/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as eventFactorySol from "./EventFactory.sol";
export { ArenaEvent__factory } from "./ArenaEvent__factory";
